import type { ProtokollPaket } from './types';

export const testDaten: ProtokollPaket[] = [
  {
    Protokollgruppe: {
      Id: 'grp-001',
      Name: 'Baustellennotiz',
      ProjektId: 'PR-4711',
      ProjektName: 'B123 Ausbau Musterstrasse',
      ProjektStammverzeichnis: '\\\\Server\\Projekte\\B123_Musterstrasse\\',
      Protokollnummer: 5,
      Vorwort: 'Protokoll der 5. Baustellenbegehung.',
      Nachwort: 'Nächster Termin: 23.03.2026',
      Themen: 'Tiefbau, Mängel, Restarbeiten',
      Bemerkung: '',
    },
    Protokoll: {
      Id: 'prot-001',
      Name: 'Baustellennotiz 5',
      Nummer: 5,
      Datum: '2026-03-09T09:00:00',
      Ort: 'Baustelle Musterstrasse',
      Autor: 'Max Mustermann',
      Vorbemerkung: '',
      Nachbemerkung: '',
      Erledigt: false,
      IstEinzelprotokoll: false,
      Erstellt: true,
      Signatur: '',
      Teilnehmer: [
        { Oid: 'adr-010', Nummer: '10010', Name: 'GSD Software mbH', Rolle: 'AG' },
        { Oid: 'adr-011', Nummer: '50001', Name: 'Adler Anton', Rolle: 'BL' },
        { Oid: 'adr-012', Nummer: '50002', Name: 'Bauer Bernd', Rolle: 'AN' },
      ],
      Verteiler: [
        { Oid: 'adr-011', Nummer: '50001', Name: 'Adler Anton', Rolle: '' },
        { Oid: 'adr-013', Nummer: '50003', Name: 'Fischer Fritz', Rolle: '' },
      ],
    },
    Protokollelemente: [
      {
        Id: 'elem-001',
        ProtokollId: 'prot-001',
        Position: '1.1',
        Positionstitel: 'Leitungsgraben Abschnitt 1+00 bis 1+50',
        Positionstext: 'Trasse im Abschnitt 1+00 bis 1+50 herstellen. Bodenaushub und Leitungsverlegung gemäß Plan.',
        Thema: 'Tiefbau',
        Status: 10,
        Termin: '2026-03-16T00:00:00',
        VerantwortlicherOid: 'adr-011',
        VerantwortlicherId: '50001',
        VerantwortlicherName: 'Adler Anton',
        Bemerkung: '',
        Erinnerung: false,
        Wert: 0,
        MobileErfassung: { GeoLat: null, GeoLon: null, GeoAccuracy: null, GeoText: null, Notiz: null, Transkript: null, Fotos: [] },
      },
      {
        Id: 'elem-002',
        ProtokollId: 'prot-001',
        Position: '1.2',
        Positionstitel: 'Verdichtungsprüfung Abschnitt 1+00',
        Positionstext: 'Verdichtungsprüfung nach Verfüllung durchführen.',
        Thema: 'Tiefbau',
        Status: 0,
        Termin: '2026-03-20T00:00:00',
        VerantwortlicherOid: 'adr-012',
        VerantwortlicherId: '50002',
        VerantwortlicherName: 'Bauer Bernd',
        Bemerkung: '',
        Erinnerung: true,
        Wert: 0,
        MobileErfassung: { GeoLat: null, GeoLon: null, GeoAccuracy: null, GeoText: null, Notiz: null, Transkript: null, Fotos: [] },
      },
      {
        Id: 'elem-003',
        ProtokollId: 'prot-001',
        Position: '2.1',
        Positionstitel: 'Schachtabdeckung Achse 1+35',
        Positionstext: 'Schachtabdeckung nicht bündig. Austausch erforderlich.',
        Thema: 'Mangel',
        Status: 11,
        Termin: '2026-03-18T00:00:00',
        VerantwortlicherOid: 'adr-010',
        VerantwortlicherId: '10010',
        VerantwortlicherName: 'GSD Software mbH',
        Bemerkung: 'Erstmals festgestellt am 09.03.2026',
        Erinnerung: false,
        Wert: 0,
        MobileErfassung: { GeoLat: null, GeoLon: null, GeoAccuracy: null, GeoText: null, Notiz: null, Transkript: null, Fotos: [] },
      },
      {
        Id: 'elem-004',
        ProtokollId: 'prot-001',
        Position: '2.2',
        Positionstitel: 'Riss in Bodenplatte Gebäude C',
        Positionstext: 'Haarriss in Bodenplatte, ca. 2m Länge. Gutachter hinzuziehen.',
        Thema: 'Mangel',
        Status: 11,
        Termin: '2026-03-25T00:00:00',
        VerantwortlicherOid: 'adr-012',
        VerantwortlicherId: '50002',
        VerantwortlicherName: 'Bauer Bernd',
        Bemerkung: '',
        Erinnerung: true,
        Wert: 2500.0,
        MobileErfassung: { GeoLat: null, GeoLon: null, GeoAccuracy: null, GeoText: null, Notiz: null, Transkript: null, Fotos: [] },
      },
      {
        Id: 'elem-005',
        ProtokollId: 'prot-001',
        Position: '3.1',
        Positionstitel: 'Baustelleneinrichtung prüfen',
        Positionstext: 'Absperrungen und Beschilderung kontrollieren.',
        Thema: 'Allgemein',
        Status: 20,
        Termin: '2026-03-10T00:00:00',
        VerantwortlicherOid: 'adr-011',
        VerantwortlicherId: '50001',
        VerantwortlicherName: 'Adler Anton',
        Bemerkung: 'Erledigt - alles in Ordnung.',
        Erinnerung: false,
        Wert: 0,
        MobileErfassung: { GeoLat: 50.3245, GeoLon: 11.285, GeoAccuracy: 5, GeoText: 'Standort: 50.3245000, 11.2850000 (Genauigkeit 5 m)', Notiz: 'Alles ok', Transkript: null, Fotos: [] },
      },
      {
        Id: 'elem-006',
        ProtokollId: 'prot-001',
        Position: '3.2',
        Positionstitel: 'Sicherheitsunterweisung neue Mitarbeiter',
        Positionstext: 'Unterweisung für 3 neue Mitarbeiter der Fa. Bauer durchführen.',
        Thema: 'Info',
        Status: 17,
        Termin: '2026-03-09T00:00:00',
        VerantwortlicherOid: 'adr-010',
        VerantwortlicherId: '10010',
        VerantwortlicherName: 'GSD Software mbH',
        Bemerkung: 'Durchgeführt am 09.03.',
        Erinnerung: false,
        Wert: 0,
        MobileErfassung: { GeoLat: null, GeoLon: null, GeoAccuracy: null, GeoText: null, Notiz: null, Transkript: null, Fotos: [] },
      },
    ],
  },
];
